In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [ ]:
df1 = pd.read_excel('/content/gdrive/MyDrive/IV_midterm/1 SDOH_2013_Codebook_1_0.xlsx')
df2 = pd.read_excel('/content/gdrive/MyDrive/IV_midterm/2 SDOH_2013_COUNTY_1_0.xlsx')
df3 = pd.read_excel('/content/gdrive/MyDrive/IV_midterm/3 SDOH_2013_ZIPCODE_1_0.xlsx')
df4 = pd.read_excel('/content/gdrive/MyDrive/IV_midterm/4 sdoh_2013_tract_1_0.xlsx')

In [ ]:
df1.head(20)

   SDOH Database 2013 Codebook Summary & Introduction
0                        Purpose of the SDOH Database
1   Incorporating SDOH data into research that sup...
2                Purpose and Contents of the Codebook
3   This variable codebook was developed to provid...
4   The fields contained in the county, ZIP Code, ...
5   Domain: Variables in the SDOH Database were se...
6   SDOH Topic Area: For each domain, there are 1 ...
7   Variable Name: The variable name as it appears...
8   Variable Label: A descriptive label for the va...
9   Data Source: The original source of the variab...
10  Type of Data: The variable type (numeric or ch...
11  SAS Length: The variable’s SAS length as it ap...
12  SAS Character: The variable’s SAS character as...
13  Position in the file: The variable’s position ...
14  The fields contained in the County-SUMMARY, ZI...
15  Descriptive statistics for continuous variable...
16  Descriptive statistics for categorical variabl...
17                                     Note to Users:
18  The data contained in the SDOH Database are dr...

In [ ]:
df2.head()

NameError: ignored

In [ ]:
df3.head(20)

,name,label,type,length,format
0,YEAR,SDOH file year,num,4,4.
1,STATEFIPS,State FIPS Code (2-digit),char,2,$2.
2,ZIPCODE,"ZIP Code, 5-digits",char,5,$5.
3,ZCTA,"ZIP Code Tabulation Area, 5-digits",char,5,$5.
4,STATE,State name,char,25,$25.
5,REGION,Census region name,char,25,$25.
6,TERRITORY,"Territory indicator (1= U.S. Territory, 0= U.S...",num,3,1.
7,POINT_ZIP,Flag for ZIPs associated bulk mail delivery po...,num,3,1.
8,ACS_TOT_POP_WT_ZC,Total weighted population (ZCTA level),num,8,12.
9,ACS_TOT_POP_US_ABOVE1_ZC,"Total population in the U.S. (ages 1 and over,...",num,8,12.
10,ACS_TOT_POP_ABOVE5_ZC,"Total population (ages 5 and over, ZCTA level)",num,8,12.
11,ACS_TOT_POP_ABOVE15_ZC,"Total population (ages 15 and over, ZCTA level)",num,8,12.
12,ACS_TOT_POP_ABOVE16_ZC,"Total population (ages 16 and over, ZCTA level)",num,8,12.
13,ACS_TOT_POP_16_19_ZC,"Total population (between ages 16 and 19, ZCTA...",num,8,12.
14,ACS_TOT_POP_ABOVE25_ZC,"Total population (ages 25 and over, ZCTA level)",num,8,12.
15,ACS_TOT_CIVIL_POP_ABOVE18_ZC,"Total civilian population (ages 18 and over, Z...",num,8,12.
16,ACS_TOT_CIVIL_VET_POP_ABOVE25_ZC,Total civilian population who are veterans (ag...,num,8,12.
17,ACS_TOT_OWN_CHILD_BELOW17_ZC,"Total own children (ages 17 and below, ZCTA le...",num,8,12.
18,ACS_TOT_WORKER_NWFH_ZC,Total workers who do not work from home (ages ...,num,8,12.
19,ACS_TOT_WORKER_HH_ZC,"Total workers in households (ages 16 and over,...",num,8,12.

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:
df4.head(320)

,name,label,type,length,format
0,YEAR,SDOH file year,num,3,4.
1,TRACTFIPS,State-county-census tract FIPS Code (11-digit),char,11,$11.
2,COUNTYFIPS,State-county FIPS Code (5-digit),char,5,$5.
3,STATEFIPS,State FIPS Code (2-digit),char,2,$2.
4,STATE,State name,char,25,$25.
...,...,...,...,...,...
305,POS_DIST_PED_ICU_TRACT,Distance in miles to the nearest pediatric ICU...,num,8,12.2
306,POS_DIST_OBSTETRICS_TRACT,Distance in miles to the nearest obstetrics de...,num,8,12.2
307,POS_DIST_CLINIC_TRACT,Distance in miles to the nearest health clinic...,num,8,12.2
308,POS_DIST_ALC_TRACT,Distance in miles to the nearest hospital with...,num,8,12.2
309,CEN_AIAN_NH_IND,American Indian/Alaska Native areas/Hawaiian h...,char,1,NaN

In [ ]:
df2020tract.head(1000)

,name,label,type,length,format
0,YEAR,SDOH file year,num,3,4.
1,TRACTFIPS,State-county-census tract FIPS Code (11-digit),char,11,$11.
2,COUNTYFIPS,State-county FIPS Code (5-digit),char,5,$5.
3,STATEFIPS,State FIPS Code (2-digit),char,2,$2.
4,STATE,State name,char,25,$25.
...,...,...,...,...,...
324,POS_DIST_PED_ICU_TRACT,Distance in miles to the nearest pediatric ICU...,num,8,12.2
325,POS_DIST_OBSTETRICS_TRACT,Distance in miles to the nearest obstetrics de...,num,8,12.2
326,POS_DIST_CLINIC_TRACT,Distance in miles to the nearest health clinic...,num,8,12.2
327,POS_DIST_ALC_TRACT,Distance in miles to the nearest hospital with...,num,8,12.2
328,CEN_AIAN_NH_IND,American Indian/Alaska Native areas/Hawaiian h...,char,1,NaN

In [ ]:
x= ['gopi', 'suji', 'triveni']
y=dict(enumerate(x))
y

{0: 'gopi', 1: 'suji', 2: 'triveni'}

In [1]:
import numpy as np 
from tensorflow import keras
int_sequence = np.arange(20)
dummy_dataset = keras.utils.timeseries_dataset_from_array(
 data=int_sequence[1:], 
 targets=int_sequence[:-6],
 sequence_length=5,
 batch_size=2, 
)
for inputs, targets in dummy_dataset:
    for i in range(inputs.shape[0]):
        print([int(x) for x in inputs[i]], int(targets[i]))

[1, 2, 3, 4, 5] 0
[2, 3, 4, 5, 6] 1
[3, 4, 5, 6, 7] 2
[4, 5, 6, 7, 8] 3
[5, 6, 7, 8, 9] 4
[6, 7, 8, 9, 10] 5
[7, 8, 9, 10, 11] 6
[8, 9, 10, 11, 12] 7
[9, 10, 11, 12, 13] 8
[10, 11, 12, 13, 14] 9
[11, 12, 13, 14, 15] 10
[12, 13, 14, 15, 16] 11
[13, 14, 15, 16, 17] 12
[14, 15, 16, 17, 18] 13