In [1]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/content/gdrive/MyDrive/ML group Proj 2/IMDB Dataset.csv')

In [5]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

Warning: total number of rows (50000) exceeds max_rows (20000). Limiting to first (20000) rows.